package de.caluga.morphium.quarkus.data;

import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionStage;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Runtime bridge called by Gizmo-generated repository methods for query derivation.
 * Parses the method name (cached) and delegates to {@link QueryExecutor}.
 */
public final class QueryMethodBridge {

    private static final ConcurrentHashMap<String, QueryDescriptor> CACHE = new ConcurrentHashMap<>();

    private QueryMethodBridge() {}

    /**
     * Called from generated bytecode for each derived query method invocation.
     *
     * @param repo            the repository instance (provides Morphium + metadata)
     * @param methodName      the repository method name (e.g. "findByStatus")
     * @param args            the method arguments
     * @param returnsSingle   whether the caller expects a single result (T)
     * @param returnsOptional whether the caller expects an Optional result
     * @param returnsBoolean  whether the caller expects a boolean result (for deleteBy*)
     * @param returnsStream   whether the caller expects a Stream result
     * @return the query result
     */
    public static Object executeQuery(AbstractMorphiumRepository<?, ?> repo,
                                      String methodName,
                                      Object[] args,
                                      boolean returnsSingle,
                                      boolean returnsOptional,
                                      boolean returnsBoolean,
                                      boolean returnsStream) {
        String cacheKey = repo.getMetadata().entityClass().getName() + "#" + methodName;

        QueryDescriptor descriptor = CACHE.computeIfAbsent(cacheKey, k ->
                MethodNameParser.parse(methodName, null));

        // Override return type if caller expects single, optional, or stream result
        if (descriptor.prefix() == QueryDescriptor.Prefix.FIND) {
            if (returnsOptional) {
                descriptor = new QueryDescriptor(
                        descriptor.prefix(),
                        descriptor.conditions(),
                        descriptor.combinator(),
                        descriptor.orderBy(),
                        QueryDescriptor.ReturnType.OPTIONAL);
            } else if (returnsSingle) {
                descriptor = new QueryDescriptor(
                        descriptor.prefix(),
                        descriptor.conditions(),
                        descriptor.combinator(),
                        descriptor.orderBy(),
                        QueryDescriptor.ReturnType.SINGLE);
            } else if (returnsStream) {
                descriptor = new QueryDescriptor(
                        descriptor.prefix(),
                        descriptor.conditions(),
                        descriptor.combinator(),
                        descriptor.orderBy(),
                        QueryDescriptor.ReturnType.STREAM);
            }
        }

        Object result = QueryExecutor.execute(descriptor, args, repo);

        // For deleteBy* with boolean return: convert count > 0
        if (returnsBoolean && result instanceof Long count) {
            return count > 0;
        }

        return result;
    }

    public static CompletionStage<Object> executeQueryAsync(AbstractMorphiumRepository<?, ?> repo,
                                                             String methodName,
                                                             Object[] args,
                                                             boolean returnsSingle,
                                                             boolean returnsOptional,
                                                             boolean returnsBoolean,
                                                             boolean returnsStream) {
        return CompletableFuture.supplyAsync(
                () -> executeQuery(repo, methodName, args, returnsSingle, returnsOptional, returnsBoolean, returnsStream),
                repo.getAsyncExecutor());
    }
}
