package de.caluga.morphium.quarkus.data;

import java.util.List;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Runtime bridge called by Gizmo-generated repository methods for query derivation.
 * Parses the method name (cached) and delegates to {@link QueryExecutor}.
 */
public final class QueryMethodBridge {

    private static final ConcurrentHashMap<String, QueryDescriptor> CACHE = new ConcurrentHashMap<>();

    private QueryMethodBridge() {}

    /**
     * Called from generated bytecode for each derived query method invocation.
     *
     * @param repo          the repository instance (provides Morphium + metadata)
     * @param methodName    the repository method name (e.g. "findByStatus")
     * @param args          the method arguments
     * @param returnsSingle whether the caller expects a single result
     * @return the query result
     */
    public static Object executeQuery(AbstractMorphiumRepository<?, ?> repo,
                                      String methodName,
                                      Object[] args,
                                      boolean returnsSingle) {
        String cacheKey = repo.getMetadata().entityClass().getName() + "#" + methodName;

        QueryDescriptor descriptor = CACHE.computeIfAbsent(cacheKey, k ->
                MethodNameParser.parse(methodName, null));

        // Override return type if caller expects single result
        if (returnsSingle && descriptor.prefix() == QueryDescriptor.Prefix.FIND) {
            descriptor = new QueryDescriptor(
                    descriptor.prefix(),
                    descriptor.conditions(),
                    descriptor.combinator(),
                    descriptor.orderBy(),
                    QueryDescriptor.ReturnType.SINGLE);
        }

        return QueryExecutor.execute(descriptor, args, repo);
    }
}
